### PR TITLE
Modified argument validation and metric_namespace for dev.dockstore.net

### PR DESCRIPTION
**Pull request by kathy-t**
Removed argument validation that checks the specific log group name passed in. If the log group doesn't exist, Cloudwatch will display an error later in the script when it tries to fetch existing metrics for the log group.

Modified the metric_namespace variable assignment so it's more dynamic. For example, if the log group is dev.dockstore.net, the metric_namespace is DevLogMetrics. If it's staging.dockstore.org, the metric_namespace is StagingLogMetric.

dockstore.org metrics are currently in the ProductionLogMetrics namespace on Cloudwatch, but there's only 4 metrics for production, so I'll just move them over to DockstoreLogMetrics once this PR is merged.

### CODE REVIEW

**Comment by denis-yuen** [comment]
> Modified the metric_namespace variable assignment so it's more dynamic. For example, if the log group is dev.dockstore.net, the metric_namespace is DevLogMetrics. If it's staging.dockstore.org, the metric_namespace is StagingLogMetric.

Hmmm, in that case dev.dockstore.net would have the same metric namespace as dev.dockstore.org. Can metric namespaces use dashes or underscores?

On the other-hand, they are in separate AWS accounts altogether, so maybe not a big deal. 

Not sure if we'll ever have two environments with a shared prefix in the same AWS account.

**Comment by kathy-t** [comment]
> > Modified the metric_namespace variable assignment so it's more dynamic. For example, if the log group is dev.dockstore.net, the metric_namespace is DevLogMetrics. If it's staging.dockstore.org, the metric_namespace is StagingLogMetric.
> 
> Hmmm, in that case dev.dockstore.net would have the same metric namespace as dev.dockstore.org. Can metric namespaces use dashes or underscores?
> 
> On the other-hand, they are in separate AWS accounts altogether, so maybe not a big deal.
> 
> Not sure if we'll ever have two environments with a shared prefix in the same AWS account.

Metric namespaces can use: alphanumeric characters (0-9A-Za-z), period (.), hyphen (-), underscore (_), forward slash (/), hash (#), and colon (:).

Is there a convention we want to use for metric namespaces?

**Comment by denis-yuen** [comment]
> Is there a convention we want to use for metric namespaces?

Up to us really. 
If periods are allowed, is there anything wrong with simply doing with dev.dockstore.net_LogMetrics?

**Comment by kathy-t** [comment]
> > Is there a convention we want to use for metric namespaces?
> 
> Up to us really.
> If periods are allowed, is there anything wrong with simply doing with dev.dockstore.net_LogMetrics?

I don't see anything wrong with it. My only concern would be that we have existing staging metrics in the StagingLogMetrics namespace, so we would have to move those metrics over to staging.dockstore.org_LogMetrics if we choose to follow this naming convention

**Comment by denis-yuen** [comment]
> I don't see anything wrong with it. My only concern would be that we have existing staging metrics in the StagingLogMetrics namespace, so we would have to move those metrics over to staging.dockstore.org_LogMetrics if we choose to follow this naming convention

Fair enough, I think it is probably worth it

**Pull request merged**
